"""empty message

Revision ID: 71cfdfa510c4
Revises: 2d78f69bc608
Create Date: 2020-06-17 17:07:37.995198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71cfdfa510c4'
down_revision = '2d78f69bc608'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'title')
    # ### end Alembic commands ###
